services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server.
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
  notification-service:
    build: ./notification-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
  task-service:
    build: ./task-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/health" ]
      interval: 30s
      timeout: 10s
      retries: 3